### ISSUE TITLE
Øving04

### ISSUE THREAD

**Issue by dewdar** [dewdar/NTNU-CSHARP-innleveringer#2]
- Selg billetter metodene må skrives om

**Comment by lemasalamov** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication4
{
    public class Tribune
    {
        public Tribune(string navn, double pris, int kap, bool rab)
        {
            Navn = navn;
            Pris = pris;
            Kapasitet = kap; ;
            Rabatt = rab;
            if (Rabatt)
            {
                this.setRabatt();
            }

            SolgtFor = 0;
        }

        public string Navn
        {
            get;
            private set;
        }

        public double Pris
        {
            get;
            private set;
        }

        public int Kapasitet
        {
            get;
            private set;
        }
        public virtual bool Rabatt
        {
            get;
            private set;
        }
        virtual public void setRabatt() { this.Pris = Pris / 2; }

        public double SolgtFor;
        public virtual int AntallSolgtePlasser
        {
            get
            {
                return 0;
            }
        }
        public override string ToString()
        {
            return Navn + " har kapasitet " + Kapasitet + " og pris " + Pris + " kroner.";
        }
    }


    public class Ståtribune : Tribune
    {
        private int antallSolgtePlasser;
        public Ståtribune(string navn, double pris, int kap, bool rab)
            : base(navn, pris, kap, rab)
        {
            antallSolgtePlasser = 0;
        }
        public override int AntallSolgtePlasser
        {
            get
            {
                return antallSolgtePlasser;
            }
        }

        public Billett.Ståbilett[] KjøpBillett(int voksen, int barn)
        {
            if (SelgPlasser(voksen + barn))
            {
                Billett.Ståbilett[] Results = new Billett.Ståbilett[voksen];
                for (int i = 0; 1 < voksen; i++)
                {
                    Billett.Ståbilett V = new Billett.Ståbilett(this.Navn, this.Pris);
                    SolgtFor += Pris;
                    Results[i] = V;
                }
                for (int j = voksen; j < voksen + barn; j++)
                {
                    Billett.Ståbilett B = new Billett.Ståbilett(this.Navn, this.Pris);
                    Results[j] = B;
                    SolgtFor += Pris / 2;
                }
                return Results;
            }
            else { return null; }
        }

        public bool SelgPlasser(int antall)
        {
            if (AntallSolgtePlasser + antall <= Kapasitet)
            {
                antallSolgtePlasser += antall;
                return true;
            }
            else return false;
        }
    }

    public class Sittetribune : Tribune
    {
        private int[] antallSolgtPrRad;

        public Sittetribune(string navn, double pris, int kap, int antRader, bool rab)
            : base(navn, pris, kap, rab)
        {
            AntallRader = antRader;
            antallSolgtPrRad = new int[AntallRader];
            for (int i = 0; i < AntallRader; i++) antallSolgtPrRad[i] = 0;
        }

        public int AntallRader
        {
            get;
            private set;
        }

        public override int AntallSolgtePlasser
        {
            get
            {
                int total = 0;
                for (int i = 0; i < AntallRader; i++) total += antallSolgtPrRad[i];
                return total;
            }
        }
        public Billett.Sittebilett[] KjøpBillett(int voksen, int barn)
        {
            if (SelgPlasser(voksen + barn))
            {
                Billett.Sittebilett[] Results = new Billett.Sittebilett[voksen];
                for (int i = 0; 1 < voksen; i++)
                {
                    Billett.Sittebilett V = new Billett.Sittebilett(this.Navn, this.Pris, );
                    Results[i] = V;
                    SolgtFor += Pris;
                }
                for (int j = voksen; j < voksen + barn; j++)
                {
                    Billett.Sittebilett B = new Billett.Sittebilett(this.Navn, this.Pris);
                    Results[j] = B;
                    SolgtFor += Pris / 2;
                }
                return Results;
            }
            else { return null; }
        }
        /* MÅ FIKSES RETURN TYPE FOR AT DET SKAL VISE I TILLEGG RADNR OG PLASSNR */
        private bool SelgPlasser(int antall)
        {
            int kapPrRad = Kapasitet / AntallRader;
            int i = 0;
            while (i < AntallRader && antallSolgtPrRad[i] + antall > kapPrRad) i++;
            if (i < AntallRader)
            {
                antallSolgtPrRad[i] += antall;
                Console.WriteLine(i + 1 + " " + antallSolgtPrRad[i + 1]);
                return true;

            }
            else return false;
        }
        public override string ToString()
        {
            return base.ToString() + " Antall rader er " + AntallRader + ".";
        }
    }

    public class VIPtribune : Sittetribune
    {
        private string[,] tilskuer;

        public VIPtribune(string navn, double pris, int kap, int antRader, bool rab)
            : base(navn, pris, kap, antRader, rab)
        {
            int antPrRad = Kapasitet / AntallRader;
            tilskuer = new string[AntallRader, antPrRad];
        }
        public override void setRabatt()
        {
            //base.setRabatt();
        }
    }
}
